# Generated by Django 4.2.4 on 2023-08-26 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default='Другое', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dishes', to='recipes.category'),
        ),
    ]
